# Cleaning the Station Files

### Local Imports

In [1]:
from cs1.tools import *

In [2]:
cd(BASE_DIR)

'/home/fuzzy/DataAnalysisLab/Case_Study_1'

In [14]:
sys.version

NameError: name 'sys' is not defined

### Station Files

In [3]:
STATION_FILES

[PosixPath('/home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2015.csv'),
 PosixPath('/home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Trips_2016_Q1Q2/Divvy_Stations_2016_Q1Q2.csv'),
 PosixPath('/home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2017_Q1Q2.csv'),
 PosixPath('/home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2017_Q3Q4.csv'),
 PosixPath('/home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_Trips_2013/Divvy_Stations_2013.csv'),
 PosixPath('/home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2016_Q4.csv'),
 PosixPath('/home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2016_Q3.csv'),
 PosixPath('/home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_Trips_2014_Q3Q4/Divvy_Stations_2014-Q3Q4.csv')]

In [4]:
station_cols = list()
for p in STATION_FILES:
    with p.open() as f:
        new_list = [s.strip().strip('"') for s in next(f).strip().split(',')]
        while len(new_list) < MAX_COLS:
            new_list.append('')
        station_cols.append(new_list)

set([str(L) for L in station_cols])

{"['id', 'name', 'city', 'latitude', 'longitude', 'dpcapacity', 'online_date', '', '', '', '', '', '', '']",
 "['id', 'name', 'latitude', 'longitude', 'dpcapacity', 'dateCreated', '', '', '', '', '', '', '', '']",
 "['id', 'name', 'latitude', 'longitude', 'dpcapacity', 'landmark', '', '', '', '', '', '', '', '']",
 "['id', 'name', 'latitude', 'longitude', 'dpcapacity', 'landmark', 'online date', '', '', '', '', '', '', '']",
 "['id', 'name', 'latitude', 'longitude', 'dpcapacity', 'online_date', '', '', '', '', '', '', '', '']"}

In [5]:
new_station_cols = ['ID', 'Name', 'City', 'Latitude', 'Longitude', 'DP Capacity', 'Landmark', 'Online Date']

In [6]:
cols = dict()
for i in range(len(new_station_cols)):
    cols[new_station_cols[i]] = list()

cols['ID'] = 'id'
cols['Name'] = 'name'
cols['City'] = 'city'
cols['Latitude'] = 'latitude'
cols['Longitude'] = 'longitude'
cols['DP Capacity'] = 'dpcapacity'
cols['Landmark'] = 'landmark'
cols['Online Date'] = ['online date', 'online_date', 'dateCreated']

In [7]:
cols

{'ID': 'id',
 'Name': 'name',
 'City': 'city',
 'Latitude': 'latitude',
 'Longitude': 'longitude',
 'DP Capacity': 'dpcapacity',
 'Landmark': 'landmark',
 'Online Date': ['online date', 'online_date', 'dateCreated']}

In [12]:
def combine_station_files():
    df_sum = pd.DataFrame()
    for f in STATION_FILES:
    #     if not f.name == 'Divvy_Stations_2017_Q3Q4.csv':
        print(f'Processing {f}')
        df = pd.read_csv(f)
        new_cols = list()
        UNNAMED = False
        for s in df.columns:
            if regex_in_list(r'Unnamed: \d', df.columns):
                print("Dropping column...")
                df = df.drop("Unnamed: 7", axis=1)
        for s in df.columns:
            try:
                k = reverse_lookup(cols, s)
                assert(k)
            except AssertionError as e:
                print(f'Bad lookup value: {s}')
                print(f'File: {f.name}')
            new_cols.append(k)
    #     try:    
    #         df.columns = new_cols
    #         df.reindex(columns=new_station_cols)
    # #         print(df.head())
    #     except ValueError as e:
    #         print(f'Value Error: {f}')
    #         print_exc()
        if not len(df_sum):
            df_sum = df
        else:
            df_sum = pd.concat([df_sum, df])

    #     print(df_sum.describe())
        print(f'{len(df_sum)=}\n')
    
    return df_sum.sort_values("ID")

In [13]:
combine_station_files()

Processing /home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2015.csv
len(df_sum)=474

Processing /home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Trips_2016_Q1Q2/Divvy_Stations_2016_Q1Q2.csv
len(df_sum)=1009

Processing /home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2017_Q1Q2.csv
len(df_sum)=1591

Processing /home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2017_Q3Q4.csv
Bad lookup value: Unnamed: 7
File: Divvy_Stations_2017_Q3Q4.csv
Dropping column...
len(df_sum)=2176

Processing /home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_Trips_2013/Divvy_Stations_2013.csv
len(df_sum)=2476

Processing /home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2016_Q4.csv
len(df_sum)=3057

Processing /home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_2016_Q3.csv
len(df_sum)=3638

Processing /home/fuzzy/DataAnalysisLab/Case_Study_1/data/Divvy_Stations_Trips_2014_Q3Q4/Divvy_Stations_2014-Q3Q4.csv
len(df_sum)=3938

KeyError: 'ID'

In [11]:
df

,ID,Name,Latitude,Longitude,DP Capacity,Landmark,Online Date,City
0,2,Michigan Ave & Balbo Ave,41.872293,-87.624091,35,541.0,NaN,NaN
47,2,Buckingham Fountain,41.872667,-87.623971,35,NaN,5/8/2015,NaN
0,2,Buckingham Fountain,41.876393,-87.620328,27,NaN,6/10/2013 10:43,Chicago
47,2,Buckingham Fountain,41.872667,-87.623971,35,NaN,5/8/2015,NaN
0,2,Michigan Ave & Balbo Ave,41.872293,-87.624091,35,541.0,NaN,NaN
...,...,...,...,...,...,...,...,...
582,624,Dearborn St & Van Buren St (*),41.876268,-87.629155,16,NaN,7/26/2017 21:25,Chicago
583,625,Chicago Ave & Dempster St,42.041691,-87.680687,15,NaN,8/11/2017 16:53,Evanston
583,625,Chicago Ave & Dempster St,42.041691,-87.680687,15,NaN,8/11/2017 16:53,Evanston
584,626,Delano Ct & Roosevelt Rd,41.867491,-87.632190,19,NaN,12/21/2017 22:06,Chicago
584,626,Delano Ct & Roosevelt Rd,41.867491,-87.632190,19,NaN,12/21/2017 22:06,Chicago

In [12]:
df.columns

Index(['ID', 'Name', 'Latitude', 'Longitude', 'DP Capacity', 'Landmark',
       'Online Date', 'City'],
      dtype='object')

In [13]:
len(df['ID'].unique())

586

In [14]:
backup_df = df.copy()

In [16]:
# df = backup_df

In [17]:
df["Name"] = df["Name"].replace(' (\*)', '')

In [19]:
type(df["Online Date"].dtype)

numpy.dtype[object_]

In [21]:
new_df = pd.DataFrame()
print("Running")
IDs = df['ID'].unique()
print(f'{len(IDs)=}')
print()
for i in IDs:
    print(f'{i=}')
    df2 = df[df['ID']==i].sort_values("Online Date", ascending=False)
#     df2.reindex(index=range(len(df2)))
#     print(df2)
    print()
    
    L = list()
    for s in df2["Online Date"].dropna():
        try:
            L.append(parse(s).date())
        except TypeError as e:
            print(f"""
TYPE ERROR:
Online Date String: {s}
                  """)
    L = set(L)
    print(f'Online Dates: {L}')
    print(f'Most recent date: {max(L)}')
    most_recent_date = max(L)
    
    names = list()
    for s, n in zip(df2["Online Date"], df2["Name"]):
        try:
#             print(type(s))
#             print(f'{s=}\n{n=}')
            if type(s) is str and parse(s).date() == most_recent_date:
                names.append(n)
        except:
            pass
    print(f'{names=}')
    unique_names = list(set(names))
    unique_names.sort()
    print(f'{unique_names=}')
    d = dict()
    C = ["Name","Popularity"]
    for c in C:
        d[c] = list()
    for n in unique_names:
        d["Name"].append(n)
        d["Popularity"].append(len(df2[df2["Name"] == n]))
    print(d)
    popular_names = pd.DataFrame(d).sort_values("Popularity", ascending=False)
    print(popular_names)
    name = popular_names["Name"][0]
    print(f'{name=}')
    
    C = df2['City'].dropna()
    city = None
    print(f'{C=}')
    if C.any():
        for c in C:
            city = c
            break
#     print(f'{type(city)=}')

    lats = df2["Latitude"]
    diff = max(lats) - min(lats) if len(df2) > 1 else 0
    if diff > 0.01:
        print("WARNING: Difference in latitude > 0.01")
        print(f'{len(df2)=}')
        print(f'{max(lats)=}')
        print(f'{min(lats)=}')
        print(f'{diff=}')
        print(i)
        print()
    lons = df2["Longitude"]
    diff = max(lons) - min(lons) if len(df2) > 1 else 0
    if diff > 0.01:
        print("WARNING: Difference in longitude > 0.01")
        print(f'{len(df2)=}')
        print(f'{max(lons)=}')
        print(f'{min(lons)=}')
        print(f'{diff=}')
        print(i)
        print()
    if (lats < 40).any() or (lats > 43).any() or (lons < -89).any() or (lons > -85).any():
        print("WARNING: Unreasonable latitude and/or longitude!")
        print(i)
        print()
        
    latitude = mean(lats)
    longitude = mean(lons)
    print(f'{city=}')
    print(f'{latitude=}')
    print(f'{longitude=}')
    
    C = df2['DP Capacity'].dropna()
    dpcapacity = None
#     print(f'{C=}')
    if C.any():
        for c in C:
            dpcapacity = c
            break
            
    C = df2['Landmark'].dropna()
    landmark = None
#     print(f'{C=}')
    if C.any():
        for c in C:
            landmark = c
            break
            
    d = {"ID": [i],
         "Name": [name],
         "Latitude": [latitude],
         "Longitude": [longitude],
         "City": [city],
         "DP Capacity": [dpcapacity],
         "Landmark": [landmark],
         "Online Date": [most_recent_date]}
            
    row = pd.DataFrame(d, index=[i]) # dtype=[("ID", int), ("Name", str), ("Latitude", float), ("Longitude", float), ("City", str),
                                       #     ("DP Capacity", int), ("Landmark", float), ("Online Date", str)])
            
    new_df = pd.concat([new_df, row])
    
    print()

#     if i > 5:
#         break
        
print(new_df)

Running
len(IDs)=586

i=2

Online Dates: {datetime.date(2015, 5, 8), datetime.date(2013, 6, 10)}
Most recent date: 2015-05-08
names=['Buckingham Fountain', 'Buckingham Fountain', 'Michigan Ave & Balbo Ave', 'Michigan Ave & Balbo Ave', 'Michigan Ave & Balbo Ave', 'Michigan Ave & Balbo Ave']
unique_names=['Buckingham Fountain', 'Michigan Ave & Balbo Ave']
{'Name': ['Buckingham Fountain', 'Michigan Ave & Balbo Ave'], 'Popularity': [6, 6]}
                       Name  Popularity
0       Buckingham Fountain           6
1  Michigan Ave & Balbo Ave           6
name='Buckingham Fountain'
C=52    Chicago
52    Chicago
0     Chicago
0     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.87461483333333
longitude=-87.62263899999999

i=3

Online Dates: {datetime.date(2015, 4, 24), datetime.date(2013, 6, 10)}
Most recent date: 2015-04-24
names=['Shedd Aquarium', 'Shedd Aquarium', 'Shedd Aquarium', 'Shedd Aquarium', 'Shedd Aquarium', 'Shedd Aquarium']
unique_names=['Shedd Aquarium']
{'Name': ['Shedd Aquarium'], 'Popularity': [12]}
             Name  Popularity
0  Shedd Aquarium          12
name='Shedd Aquarium'
C=440    Chicago
440    Chicago
1      Chicago
1      Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.867225966136665
longitude=-87.61535532503335

i=4

Online Dates: {datetime.date(2015, 5, 16), datetime.date(2013, 6, 10)}
Most recent date: 2015-05-16
names=['Burnham Harbor', 'Burnham Harbor', 'Burnham Harbor', 'Burnham Harbor', 'Burnham Harbor', 'Burnham Harbor']
unique_names=['Burnham Harbor']
{'Name': ['Burnham Harbor'], 'Popularity': [12]}
             Name  Popularity
0  Burnham Harbor          12
name='Burnham Harbor'
C=54    Chicago
54    Chicago
2     Chicago
2     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.856268
longitude=-87.61334799999999

i=5

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 18), datetime.date(2013, 6, 10)}
Most recent date: 2013-06-28
names=['State St & Harrison St', 'State St & Harrison St']
unique_names=['State St & Harrison St']
{'Name': ['State St & Harrison St'], 'Popularity': [16]}
                     Name  Popularity
0  State St & Harrison St          16
name='State St & Harrison St'
C=480    Chicago
480    Chicago
3      Chicago
3      Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.874029265000004
longitude=-87.6277218725

i=6

Online Dates: {datetime.date(2015, 4, 24), datetime.date(2013, 6, 10)}
Most recent date: 2015-04-24
names=['DuSable Harbor', 'Dusable Harbor', 'DuSable Harbor', 'Dusable Harbor', 'Dusable Harbor', 'Dusable Harbor']
unique_names=['DuSable Harbor', 'Dusable Harbor']
{'Name': ['DuSable Harbor', 'Dusable Harbor'], 'Popularity': [2, 10]}
             Name  Popularity
1  Dusable Harbor          10
0  DuSable Harbor           2
name='DuSable Harbor'
C=182    Chicago
182    Chicago
4      Chicago
4      Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.88504182705333
longitude=-87.61279452656667

i=7

Online Dates: {datetime.date(2015, 4, 18), datetime.date(2013, 6, 19)}
Most recent date: 2015-04-18
names=['Field Blvd & South Water St', 'Field Blvd & South Water St', 'Field Blvd & South Water St', 'Field Blvd & South Water St', 'Field Blvd & South Water St', 'Field Blvd & South Water St']
unique_names=['Field Blvd & South Water St']
{'Name': ['Field Blvd & South Water St'], 'Popularity': [12]}
                          Name  Popularity
0  Field Blvd & South Water St          12
name='Field Blvd & South Water St'
C=201    Chicago
201    Chicago
5      Chicago
5      Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.88634905044833
longitude=-87.61751662451667

i=9

Online Dates: {datetime.date(2013, 6, 21), datetime.date(2015, 4, 14)}
Most recent date: 2015-04-14
names=['Leavitt St & Archer Ave', 'Leavitt St & Archer Ave', 'Leavitt St & Archer Ave', 'Leavitt St & Archer Ave', 'Leavitt St & Archer Ave', 'Leavitt St & Archer Ave']
unique_names=['Leavitt St & Archer Ave']
{'Name': ['Leavitt St & Archer Ave'], 'Popularity': [12]}
                      Name  Popularity
0  Leavitt St & Archer Ave          12
name='Leavitt St & Archer Ave'
C=6      Chicago
6      Chicago
306    Chicago
306    Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.82879201665666
longitude=-87.68060438323334

i=11

Online Dates: {datetime.date(2015, 4, 22), datetime.date(2013, 6, 21)}
Most recent date: 2015-04-22
names=['Jeffery Blvd & 71st St', 'Jeffery Blvd & 71st St', 'Jeffery Blvd & 71st St', 'Jeffery Blvd & 71st St', 'Jeffery Blvd & 71st St', 'Jeffery Blvd & 71st St']
unique_names=['Jeffery Blvd & 71st St']
{'Name': ['Jeffery Blvd & 71st St'], 'Popularity': [12]}
                     Name  Popularity
0  Jeffery Blvd & 71st St          12
name='Jeffery Blvd & 71st St'
C=7      Chicago
7      Chicago
252    Chicago
252    Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.76663819949167
longitude=-87.57645009235

i=12

Online Dates: {datetime.date(2015, 4, 22), datetime.date(2013, 6, 21)}
Most recent date: 2015-04-22
names=['South Shore Dr & 71st St', 'South Shore Dr & 71st St', 'South Shore Dr & 71st St', 'South Shore Dr & 71st St', 'South Shore Dr & 71st St', 'South Shore Dr & 71st St']
unique_names=['South Shore Dr & 71st St']
{'Name': ['South Shore Dr & 71st St'], 'Popularity': [12]}
                       Name  Popularity
0  South Shore Dr & 71st St          12
name='South Shore Dr & 71st St'
C=460    Chicago
460    Chicago
8      Chicago
8      Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.76640938278333
longitude=-87.56568764198333

i=13

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 22), datetime.date(2013, 6, 20)}
Most recent date: 2013-06-28
names=['Wilton Ave & Diversey Pkwy', 'Wilton Ave & Diversey Pkwy']
unique_names=['Wilton Ave & Diversey Pkwy']
{'Name': ['Wilton Ave & Diversey Pkwy'], 'Popularity': [16]}
                         Name  Popularity
0  Wilton Ave & Diversey Pkwy          16
name='Wilton Ave & Diversey Pkwy'
C=546    Chicago
546    Chicago
9      Chicago
9      Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.93244878
longitude=-87.65269593250001

i=14

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 22), datetime.date(2013, 6, 20)}
Most recent date: 2013-06-28
names=['Morgan St & 18th St', 'Morgan St & 18th St']
unique_names=['Morgan St & 18th St']
{'Name': ['Morgan St & 18th St'], 'Popularity': [16]}
                  Name  Popularity
0  Morgan St & 18th St          16
name='Morgan St & 18th St'
C=364    Chicago
364    Chicago
10     Chicago
10     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.858086
longitude=-87.651073

i=15

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 22), datetime.date(2013, 6, 20)}
Most recent date: 2013-06-28
names=['Racine Ave & 18th St', 'Racine Ave & 18th St']
unique_names=['Racine Ave & 18th St']
{'Name': ['Racine Ave & 18th St'], 'Popularity': [14]}
                   Name  Popularity
0  Racine Ave & 18th St          14
name='Racine Ave & 18th St'
C=404    Chicago
404    Chicago
11     Chicago
11     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.85795370125
longitude=-87.65649095625

i=16

Online Dates: {datetime.date(2013, 8, 12), datetime.date(2013, 6, 22)}
Most recent date: 2013-08-12
names=['Paulina Ave & North Ave', 'Paulina Ave & North Ave', 'Wood St & North Ave', 'Paulina Ave & North Ave', 'Paulina Ave & North Ave', 'Paulina Ave & North Ave', 'Wood St & North Ave', 'Paulina Ave & North Ave']
unique_names=['Paulina Ave & North Ave', 'Wood St & North Ave']
{'Name': ['Paulina Ave & North Ave', 'Wood St & North Ave'], 'Popularity': [10, 6]}
                      Name  Popularity
0  Paulina Ave & North Ave          10
1      Wood St & North Ave           6
name='Paulina Ave & North Ave'
C=384    Chicago
384    Chicago
12     Chicago
12     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.910334
longitude=-87.67098849999999

i=17

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 22), datetime.date(2013, 6, 20)}
Most recent date: 2013-06-28
names=['Wood St & Division St', 'Wood St & Division St']
unique_names=['Wood St & Division St']
{'Name': ['Wood St & Division St'], 'Popularity': [14]}
                    Name  Popularity
0  Wood St & Division St          14
name='Wood St & Division St'
C=551    Chicago
551    Chicago
13     Chicago
13     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.903294875
longitude=-87.672880625

i=18

Online Dates: {datetime.date(2015, 4, 18), datetime.date(2013, 6, 22)}
Most recent date: 2015-04-18
names=['Wacker Dr & Washington St', 'Wacker Dr & Washington St', 'Wacker Dr & Washington St', 'Wacker Dr & Washington St', 'Wacker Dr & Washington St', 'Wacker Dr & Washington St']
unique_names=['Wacker Dr & Washington St']
{'Name': ['Wacker Dr & Washington St'], 'Popularity': [12]}
                        Name  Popularity
0  Wacker Dr & Washington St          12
name='Wacker Dr & Washington St'
C=514    Chicago
514    Chicago
14     Chicago
14     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.883248393755
longitude=-87.63731452615

i=19

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 21), datetime.date(2013, 6, 22)}
Most recent date: 2013-06-28
names=['Loomis St & Taylor St', 'Loomis St & Taylor St']
unique_names=['Loomis St & Taylor St']
{'Name': ['Loomis St & Taylor St'], 'Popularity': [8]}
                    Name  Popularity
0  Loomis St & Taylor St           8
name='Loomis St & Taylor St'
C=323    Chicago
323    Chicago
15     Chicago
15     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.869417
longitude=-87.660996

i=20

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 21), datetime.date(2013, 6, 22)}
Most recent date: 2013-06-28
names=['Sheffield Ave & Kingsbury St', 'Sheffield Ave & Kingsbury St']
unique_names=['Sheffield Ave & Kingsbury St']
{'Name': ['Sheffield Ave & Kingsbury St'], 'Popularity': [16]}
                           Name  Popularity
0  Sheffield Ave & Kingsbury St          16
name='Sheffield Ave & Kingsbury St'
C=442    Chicago
442    Chicago
16     Chicago
16     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.91017322374999
longitude=-87.65325271125

i=21

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 21), datetime.date(2013, 6, 22)}
Most recent date: 2013-06-28
names=['Aberdeen St & Jackson Blvd', 'Aberdeen St & Jackson Blvd']
unique_names=['Aberdeen St & Jackson Blvd']
{'Name': ['Aberdeen St & Jackson Blvd'], 'Popularity': [16]}
                         Name  Popularity
0  Aberdeen St & Jackson Blvd          16
name='Aberdeen St & Jackson Blvd'
C=3     Chicago
3     Chicago
17    Chicago
17    Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.87772611375
longitude=-87.65478737625

i=22

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 21), datetime.date(2013, 6, 22)}
Most recent date: 2013-06-28
names=['May St & Taylor St', 'May St & Taylor St']
unique_names=['May St & Taylor St']
{'Name': ['May St & Taylor St'], 'Popularity': [16]}
                 Name  Popularity
0  May St & Taylor St          16
name='May St & Taylor St'
C=333    Chicago
333    Chicago
18     Chicago
18     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.8694820875
longitude=-87.65548635

i=23

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 21), datetime.date(2013, 6, 22)}
Most recent date: 2013-06-28
names=['Orleans St & Elm St', 'Orleans St & Elm St']
unique_names=['Orleans St & Elm St']
{'Name': ['Orleans St & Elm St'], 'Popularity': [8]}
                  Name  Popularity
0  Orleans St & Elm St           8
name='Orleans St & Elm St'
C=381    Chicago
381    Chicago
19     Chicago
19     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.902924
longitude=-87.637715

i=24

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 21), datetime.date(2013, 6, 22)}
Most recent date: 2013-06-28
names=['Fairbanks Ct & Grand Ave', 'Fairbanks Ct & Grand Ave']
unique_names=['Fairbanks Ct & Grand Ave']
{'Name': ['Fairbanks Ct & Grand Ave'], 'Popularity': [16]}
                       Name  Popularity
0  Fairbanks Ct & Grand Ave          16
name='Fairbanks Ct & Grand Ave'
C=198    Chicago
198    Chicago
20     Chicago
20     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.89186
longitude=-87.62062

i=25

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 22)}
Most recent date: 2013-06-28
names=['Michigan Ave & Pearson St', 'Michigan Ave & Pearson St']
unique_names=['Michigan Ave & Pearson St']
{'Name': ['Michigan Ave & Pearson St'], 'Popularity': [16]}
                        Name  Popularity
0  Michigan Ave & Pearson St          16
name='Michigan Ave & Pearson St'
C=345    Chicago
345    Chicago
21     Chicago
21     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.89766
longitude=-87.62351

i=26

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 22)}
Most recent date: 2013-06-28
names=['McClurg Ct & Illinois St', 'McClurg Ct & Illinois St']
unique_names=['McClurg Ct & Illinois St']
{'Name': ['McClurg Ct & Illinois St'], 'Popularity': [16]}
                       Name  Popularity
0  McClurg Ct & Illinois St          16
name='McClurg Ct & Illinois St'
C=335    Chicago
335    Chicago
22     Chicago
22     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.89093737500001
longitude=-87.617329

i=27

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 22)}
Most recent date: 2013-06-28
names=['Larrabee St & North Ave', 'Larrabee St & North Ave']
unique_names=['Larrabee St & North Ave']
{'Name': ['Larrabee St & North Ave'], 'Popularity': [16]}
                      Name  Popularity
0  Larrabee St & North Ave          16
name='Larrabee St & North Ave'
C=297    Chicago
297    Chicago
23     Chicago
23     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.91021
longitude=-87.6435

i=28

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 22)}
Most recent date: 2013-06-28
names=['Larrabee St & Menomonee St', 'Larrabee St & Menomonee St']
unique_names=['Larrabee St & Menomonee St']
{'Name': ['Larrabee St & Menomonee St'], 'Popularity': [16]}
                         Name  Popularity
0  Larrabee St & Menomonee St          16
name='Larrabee St & Menomonee St'
C=296    Chicago
296    Chicago
24     Chicago
24     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.91468
longitude=-87.64331999999999

i=29

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 22)}
Most recent date: 2013-06-28
names=['Noble St & Milwaukee Ave', 'Noble St & Milwaukee Ave']
unique_names=['Noble St & Milwaukee Ave']
{'Name': ['Noble St & Milwaukee Ave'], 'Popularity': [16]}
                       Name  Popularity
0  Noble St & Milwaukee Ave          16
name='Noble St & Milwaukee Ave'
C=370    Chicago
370    Chicago
25     Chicago
25     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.90068
longitude=-87.6626

i=30

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 22)}
Most recent date: 2013-06-28
names=['Ashland Ave & Augusta Blvd', 'Ashland Ave & Augusta Blvd']
unique_names=['Ashland Ave & Augusta Blvd']
{'Name': ['Ashland Ave & Augusta Blvd'], 'Popularity': [16]}
                         Name  Popularity
0  Ashland Ave & Augusta Blvd          16
name='Ashland Ave & Augusta Blvd'
C=18    Chicago
18    Chicago
26    Chicago
26    Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.899643
longitude=-87.6677

i=31

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 22)}
Most recent date: 2013-06-28
names=['Franklin St & Chicago Ave', 'Franklin St & Chicago Ave']
unique_names=['Franklin St & Chicago Ave']
{'Name': ['Franklin St & Chicago Ave'], 'Popularity': [16]}
                        Name  Popularity
0  Franklin St & Chicago Ave          16
name='Franklin St & Chicago Ave'
C=206    Chicago
206    Chicago
27     Chicago
27     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.896789014999996
longitude=-87.63563564625

i=32

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 21), datetime.date(2013, 6, 22)}
Most recent date: 2013-06-28
names=['Racine Ave & Congress Pkwy', 'Racine Ave & Congress Pkwy']
unique_names=['Racine Ave & Congress Pkwy']
{'Name': ['Racine Ave & Congress Pkwy'], 'Popularity': [16]}
                         Name  Popularity
0  Racine Ave & Congress Pkwy          16
name='Racine Ave & Congress Pkwy'
C=409    Chicago
409    Chicago
28     Chicago
28     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.87464
longitude=-87.65703

i=33

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 22), datetime.date(2013, 6, 25)}
Most recent date: 2013-06-28
names=['State St & Van Buren St', 'State St & Van Buren St']
unique_names=['State St & Van Buren St']
{'Name': ['State St & Van Buren St'], 'Popularity': [16]}
                      Name  Popularity
0  State St & Van Buren St          16
name='State St & Van Buren St'
C=485    Chicago
485    Chicago
29     Chicago
29     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.877181
longitude=-87.627844

i=34

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 22), datetime.date(2013, 6, 27)}
Most recent date: 2013-06-28
names=['Cannon Dr & Fullerton Ave', 'Cannon Dr & Fullerton Ave']
unique_names=['Cannon Dr & Fullerton Ave']
{'Name': ['Cannon Dr & Fullerton Ave'], 'Popularity': [16]}
                        Name  Popularity
0  Cannon Dr & Fullerton Ave          16
name='Cannon Dr & Fullerton Ave'
C=83    Chicago
83    Chicago
30    Chicago
30    Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.926755990937494
longitude=-87.6344288081

i=35

Online Dates: {datetime.date(2013, 6, 22), datetime.date(2013, 8, 5)}
Most recent date: 2013-08-05
names=['Streeter Dr & Grand Ave', 'Streeter Dr & Grand Ave', 'Streeter Dr & Illinois St', 'Streeter Dr & Illinois St', 'Streeter Dr & Grand Ave', 'Streeter Dr & Grand Ave', 'Streeter Dr & Grand Ave', 'Streeter Dr & Grand Ave']
unique_names=['Streeter Dr & Grand Ave', 'Streeter Dr & Illinois St']
{'Name': ['Streeter Dr & Grand Ave', 'Streeter Dr & Illinois St'], 'Popularity': [10, 6]}
                        Name  Popularity
0    Streeter Dr & Grand Ave          10
1  Streeter Dr & Illinois St           6
name='Streeter Dr & Grand Ave'
C=495    Chicago
495    Chicago
31     Chicago
31     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.89182537500001
longitude=-87.61210187500001

i=36

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 24), datetime.date(2013, 6, 15)}
Most recent date: 2013-06-28
names=['Franklin St & Jackson Blvd', 'Franklin St & Jackson Blvd']
unique_names=['Franklin St & Jackson Blvd']
{'Name': ['Franklin St & Jackson Blvd'], 'Popularity': [16]}
                         Name  Popularity
0  Franklin St & Jackson Blvd          16
name='Franklin St & Jackson Blvd'
C=207    Chicago
207    Chicago
32     Chicago
32     Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.8777079644875
longitude=-87.6353211226

i=37

Online Dates: {datetime.date(2013, 6, 28), datetime.date(2013, 6, 16), datetime.date(2013, 6, 25)}
Most recent date: 2013-06-28
names=['Dearborn St & Adams St', 'Dearborn St & Adams St']
unique_names=['Dearborn St & Adams St']
{'Name': ['Dearborn St & Adams St'], 'Popularity': [16]}
                     Name  Popularity
0  Dearborn St & Adams St          16
name='Dearborn St & Adams St'
C=33     Chicago
33     Chicago
171    Chicago
171    Chicago
Name: City, dtype: object
city='Chicago'
latitude=41.8793563148375
longitude=-87.6297910345375

i=38

Online Dates: {datetime.date(2015, 4, 18), datetime.date(2013, 6, 25)}
Most recent date: 2015-04-18

In [22]:
new_df

,ID,Name,Latitude,Longitude,City,DP Capacity,Landmark,Online Date
2,2,Buckingham Fountain,41.874615,-87.622639,Chicago,27,541,2015-05-08
3,3,Shedd Aquarium,41.867226,-87.615355,Chicago,31,544,2015-04-24
4,4,Burnham Harbor,41.856268,-87.613348,Chicago,23,545,2015-05-16
5,5,State St & Harrison St,41.874029,-87.627722,Chicago,19,30,2013-06-28
6,6,DuSable Harbor,41.885042,-87.612795,Chicago,39,548,2015-04-24
...,...,...,...,...,...,...,...,...
622,622,California Ave & Cortez St,41.900363,-87.696704,Chicago,15,None,2017-04-27
623,623,Michigan Ave & 8th St,41.872773,-87.623981,Chicago,23,None,2017-06-13
624,624,Dearborn St & Van Buren St (*),41.876268,-87.629155,Chicago,16,None,2017-07-26
625,625,Chicago Ave & Dempster St,42.041691,-87.680687,Evanston,15,None,2017-08-11
626,626,Delano Ct & Roosevelt Rd,41.867491,-87.632190,Chicago,19,None,2017-12-21

In [23]:
len(new_df["Online Date"].dropna())

586

In [24]:
new_df.to_csv(str(CLEAN_DIR / 'stations.csv'), index=False)

In [25]:
df

,ID,Name,Latitude,Longitude,DP Capacity,Landmark,Online Date,City
0,2,Michigan Ave & Balbo Ave,41.872293,-87.624091,35,541.0,NaN,NaN
0,2,Buckingham Fountain,41.876393,-87.620328,27,NaN,6/10/2013 10:43,Chicago
357,2,Michigan Ave & Balbo Ave,41.872638,-87.623979,35,NaN,5/8/2015,NaN
52,2,Buckingham Fountain,41.881060,-87.619486,27,NaN,6/10/2013 10:43:46,Chicago
47,2,Buckingham Fountain,41.872667,-87.623971,35,NaN,5/8/2015,NaN
...,...,...,...,...,...,...,...,...
581,623,Michigan Ave & 8th St,41.872773,-87.623981,31,NaN,6/13/2017 15:23,Chicago
339,623,Michigan Ave & 8th St,41.872773,-87.623981,23,NaN,6/13/2017 15:23:53,Chicago
582,624,Dearborn St & Van Buren St (*),41.876268,-87.629155,16,NaN,7/26/2017 21:25,Chicago
583,625,Chicago Ave & Dempster St,42.041691,-87.680687,15,NaN,8/11/2017 16:53,Evanston
584,626,Delano Ct & Roosevelt Rd,41.867491,-87.632190,19,NaN,12/21/2017 22:06,Chicago

## Other Stations

Other station IDs were found in the CSV files describing all the bike trips.

In [ ]:
from_ids = unique_values("From Station ID")
to_ids = unique_values("To Station ID")

In [2]:
stations = pd.read_csv(CLEAN_DIR / 'stations.csv')

NameError: name 'pd' is not defined